version: 2.1.{build}
pull_requests:
  do_not_increment_build_number: true
image: Ubuntu2004
configuration: Release
only_commits:
  files:
    - '**/*.cs'
    - '**/*.csproj'
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
build:
  publish_nuget: true
  verbosity: minimal
before_test:
  - az login --service-principal --tenant 2654a8a0-11c9-4a1f-8d0a-1125f5e81496 -u d8c7ff4d-558a-425b-87fc-debc292ae362 -p $SPN_TOKEN
after_test:
  - dotnet tool restore && dotnet stryker --reporter cleartext --since=main -c 4
test_script:
  - dotnet test -s test.runsettings
environment:
  SPN_TOKEN:
    secure: Sag3dVLEaqxdGQAFyq1jQKy3oOwFLg2TgTJQxsHaagFV6qS33FAbYC5uB8LX5O4K
for:
  - branches:
      only:
        - main
        - stryker
    environment:
      CODECOV_TOKEN: 82855860-51e6-44b7-a0e4-75f725a6a7be
      STRYKER_DASHBOARD_API_KEY:
        secure: zNvmKO5DpbfDRV+WFnyaetwbAexTXGi4rMSwJH9NnTtOS3SDAUjD8CIVGRsReMRf
    after_test:
      - curl -Os https://uploader.codecov.io/latest/linux/codecov && chmod +x codecov && ./codecov -t ${CODECOV_TOKEN} -f **/*.cobertura.xml
      - dotnet tool restore && dotnet stryker -f stryker-config.yaml --reporter dashboard --dashboard-api-key $STRYKER_DASHBOARD_API_KEY -c 4
    deploy:
      - provider: NuGet
        api_key:
          secure: 6sPnG9susETMj+SCJB7ESTUOoqhVZ6OAO1W+Qb3Y0h+qjCOo5qnbev8l5ISg32hr
        on:
          branch: main
